version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API port
      - "9090:9090"  # Web UI port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server --console-address ":9090" /data
    restart: unless-stopped

volumes:
  minio_data:
